SET IDENTITY_INSERT [dbo].[Endereco] ON
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (1, 1, N'03590170', N'Rua irmao nicolau da fonseca', 217, N'53B', N'Artur Alvim', N'Sao Paulo')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (2, 1, N'03591080', N'Rua arcangelo paoli', 112, N'11A', N'Artur Alvim', N'Sao Paulo')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (3, 2, N'11075380', N'Rua Álvaro Guiao', 32156, N'Apto 55 Bloco 4', N'Vila São Bento', N'Campinas')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (4, 2, N'11070902', N'Rua Doutor Gaspar Ricardo', 896, N'Apto 105 Bloco 2', N'Parque Via Norte', N'Campinas')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (5, 5, N'11070300', N'Rua Ministro Xavier de Toledo', 21, N'Apto 57', N'Cumbica', N'Guarulhos')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (6, 5, N'11065003', N'Avenida Doutor Bernardino de Campos', 6589, N'23A', N'Jardim Fortaleza', N'Guarulhos')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (7, 6, N'11013570', N'Rua Professor Celso da Cunha Alves', 654, N'14B', N'Porto Paquetá', N'Santos')
INSERT INTO [dbo].[Endereco] ([pk_idEndereco], [fk_idCliente], [cepEndereco], [logrEndereco], [numEndereco], [complEndereco], [bairroEndereco], [cidEndereco]) VALUES (8, 6, N'11013590', N'Rua Vasco da Gama', 15, NULL, N'Morro Jabaquara', N'Santos')
SET IDENTITY_INSERT [dbo].[Endereco] OFF
