// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ClienteLogin1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClienteLogin1));
        
        string IMigrationMetadata.Id
        {
            get { return "201511081835265_ClienteLogin1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
