// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201511132042396_Endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
