// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class teste2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste2));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151635436_teste2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
