// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fk_idEndereco_Cupcake_pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_idEndereco_Cupcake_pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141613121_fk_idEndereco_Cupcake_pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
