// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cupcake_pedidoIdentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cupcake_pedidoIdentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151535080_cupcake_pedidoIdentity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
