// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NullDeNovo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullDeNovo));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141536194_NullDeNovo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
