// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class teste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151634520_teste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
