// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _13112015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13112015));
        
        string IMigrationMetadata.Id
        {
            get { return "201511132032588_13112015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
