// <auto-generated />
namespace CupcakeriaOnline.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SemidentityCupcake_Pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SemidentityCupcake_Pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141557083_SemidentityCupcake_Pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
